wdk:
  workflows.path: ""
  loader.path: ./workflows
  encrypt.passphrase: mysecretpassphrase
  properties:
    monitoring-token: mysecretpassphrase
    management-token: mysecretpassphrase
bdk:
  host: develop2.symphony.com
  bot:
    username: ys-bot
    privateKey:
      path: ../rsa/privatekey.pem
logging.level:
  org:
    springframework: error
    apache: error
    hibernate: error
  com:
    zaxxer: error
    symphony: info
    symphony.bdk.workflow:
      swadl: error
      engine.executor.DebugExecutor: debug
    symphony.bdk.spring.config: error
  springfox: error
